apiVersion: v1
kind: Service
metadata:
  name: spotify
spec:
  selector:
    app: spotify
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30112
  type: NodePort

