apiVersion: v1
kind: Service
metadata:
  name: spotify-loadbalancer
spec:
  selector:
    app: spotify
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  

